name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check Bash scripts
        run: |
          # 检查 Bash 脚本语法
          bash -n install.sh
          bash -n scripts/detect-shell.sh

      - name: Check Lua files
        run: |
          # 安装 luacheck
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

          # 检查 Lua 文件
          luacheck config/*.lua --no-unused-args || true

  test-unix:
    name: Test on Unix/Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bash zsh fish

      - name: Test shell detection
        run: |
          chmod +x scripts/detect-shell.sh
          ./scripts/detect-shell.sh

      - name: Test shell detection (JSON output)
        run: |
          OUTPUT_JSON=true ./scripts/detect-shell.sh

  test-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install fish

      - name: Test shell detection
        run: |
          chmod +x scripts/detect-shell.sh
          ./scripts/detect-shell.sh

  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test PowerShell script
        run: |
          .\scripts\detect-shell.ps1
        shell: pwsh

      - name: Test PowerShell script (JSON output)
        run: |
          .\scripts\detect-shell.ps1 -OutputJson
        shell: pwsh